-- Run this once in Supabase → SQL Editor.
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  page_path text not null,
  field_key text not null,
  kind text not null check (kind in ('text', 'image', 'link')),
  value text not null,
  label text,
  image_width integer,
  image_height integer,
  updated_at timestamptz not null default now(),
  unique (page_path, field_key)
);

alter table public.site_content enable row level security;
drop policy if exists "Public can read website content" on public.site_content;
create policy "Public can read website content" on public.site_content for select using (true);
drop policy if exists "Fresh Kind admin can add content" on public.site_content;
create policy "Fresh Kind admin can add content" on public.site_content for insert to authenticated
with check (lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');
drop policy if exists "Fresh Kind admin can update content" on public.site_content;
create policy "Fresh Kind admin can update content" on public.site_content for update to authenticated
using (lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com') with check (lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');
drop policy if exists "Fresh Kind admin can remove content" on public.site_content;
create policy "Fresh Kind admin can remove content" on public.site_content for delete to authenticated
using (lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');

insert into storage.buckets (id, name, public) values ('site-assets', 'site-assets', true)
on conflict (id) do update set public = true;
drop policy if exists "Public can view Fresh Kind assets" on storage.objects;
create policy "Public can view Fresh Kind assets" on storage.objects for select using (bucket_id = 'site-assets');
drop policy if exists "Fresh Kind admin can upload assets" on storage.objects;
create policy "Fresh Kind admin can upload assets" on storage.objects for insert to authenticated
with check (bucket_id = 'site-assets' and lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');
drop policy if exists "Fresh Kind admin can update assets" on storage.objects;
create policy "Fresh Kind admin can update assets" on storage.objects for update to authenticated
using (bucket_id = 'site-assets' and lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');
drop policy if exists "Fresh Kind admin can delete assets" on storage.objects;
create policy "Fresh Kind admin can delete assets" on storage.objects for delete to authenticated
using (bucket_id = 'site-assets' and lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');

-- Products managed from /admin/products and displayed on /our-juices.
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  flavour text not null default '',
  category text not null default 'Bottle',
  size text not null default '250 ML',
  description text not null default '',
  image_url text not null,
  accent text not null default '#8db532',
  is_active boolean not null default true,
  position integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists category text not null default 'Bottle';
alter table public.products add column if not exists accent text not null default '#8db532';
alter table public.products add column if not exists position integer not null default 100;
alter table public.products add column if not exists updated_at timestamptz not null default now();

alter table public.products enable row level security;
drop policy if exists "Public can view active products" on public.products;
create policy "Public can view active products" on public.products for select using (is_active = true or lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');
drop policy if exists "Fresh Kind admin can add products" on public.products;
create policy "Fresh Kind admin can add products" on public.products for insert to authenticated
with check (lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');
drop policy if exists "Fresh Kind admin can update products" on public.products;
create policy "Fresh Kind admin can update products" on public.products for update to authenticated
using (lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com') with check (lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');
drop policy if exists "Fresh Kind admin can delete products" on public.products;
create policy "Fresh Kind admin can delete products" on public.products for delete to authenticated
using (lower(auth.jwt() ->> 'email') = 'admin@fresh-kind.com');

insert into public.products (name, slug, flavour, category, size, description, image_url, accent, position) values
('Papaya Juice','papaya-juice','Papaya','Bottle','250 ML','Refreshing fruit flavour in a convenient bottle. Shake well and enjoy fresh.','/assets/papaya-full.png','#ee8b35',10),
('Guava Juice','guava-juice','Pink Guava','Bottle','250 ML','Refreshing fruit flavour in a convenient bottle. Shake well and enjoy fresh.','/assets/guava-full.png','#75a93e',20),
('Litchi Juice','litchi-juice','Litchi','Bottle','250 ML','Refreshing fruit flavour in a convenient bottle. Shake well and enjoy fresh.','/assets/litchi-full.png','#df6f80',30),
('Chiku Juice','chiku-juice','Chiku','Bottle','250 ML','Refreshing fruit flavour in a convenient bottle. Shake well and enjoy fresh.','/assets/chiku-full.png','#b58a5b',40),
('Pineapple Juice','pineapple-juice','Pineapple','Bottle','250 ML','Refreshing fruit flavour in a convenient bottle. Shake well and enjoy fresh.','/assets/pineapple-full.png','#e3ad20',50),
('Blueberry Boba','blueberry-boba','Blueberry','Boba','250 ML','A playful blueberry fruit drink with chewy boba pearls.','/assets/blueberry-full.png','#7257a8',60),
('Lemon Mojito Boba','lemon-mojito-boba','Lemon','Boba','250 ML','A bright lemon mojito fruit drink with chewy boba pearls.','/assets/lemon-full.png','#9dc538',70),
('Tender Coconut Water','tender-coconut-water','Tender Coconut','Tin','330 ML','Naturally hydrating coconut water with real tender coconut pulp and refreshing electrolytes.','/assets/tender-coconut.png','#8db532',80)
on conflict (slug) do nothing;
