import { PageShell } from "../site-shell";

const contacts=[["☎","Call us","+91 97411 89488","tel:+919741189488","Call now"],["☎","Alternate number","+91 6360 321 543","tel:+916360321543","Call now"],["◉","WhatsApp us","Fast help from our team","https://wa.me/919741189488","Start a chat"],["✉","Email us","info@fresh-kind.com","mailto:info@fresh-kind.com","Send email"],["⌖","Visit us","Mangalore, Dakshina Kannada","#location","View location"]];

export default function Contact(){return <PageShell accent="#79ae3d">
  <section className="contact-page-hero"><div><p className="eyebrow">Let’s talk fresh</p><h1>One conversation<br/>can start something <span>fresh.</span></h1><p>Whether you are interested in products, retail supply, distribution or bulk requirements, choose the easiest way to reach our team.</p></div><div className="contact-orbit" aria-hidden="true"><span>☎</span><span>✉</span><span>◉</span><div><img src="/assets/logo.jpg" alt=""/></div></div></section>

  <section className="contact-card-grid contact-reveal">{contacts.map(x=><a href={x[3]} key={x[1]}><i>{x[0]}</i><small>Fresh Kind</small><h2>{x[1]}</h2><p>{x[2]}</p><b>{x[4]} ↗</b></a>)}</section>

  <section className="contact-enquiry contact-reveal"><div className="contact-form-copy"><p className="eyebrow">Send an enquiry</p><h2>What can we help you with?</h2><p>Complete the form and our team will respond using the contact information you provide.</p><div className="response-note"><i>✓</i><span><b>Clear enquiry routing</b>Choose a subject so your message reaches the right person.</span></div><div className="response-note"><i>↗</i><span><b>Faster response</b>Include a phone or WhatsApp number for quick follow-up.</span></div></div><form><div className="field"><label>Your name *</label><input required placeholder="Full name"/></div><div className="field"><label>Phone number *</label><input required placeholder="+91"/></div><div className="field"><label>Email address</label><input type="email" placeholder="you@email.com"/></div><div className="field"><label>Subject *</label><select defaultValue=""><option value="" disabled>Choose a subject</option><option>Product enquiry</option><option>Distributor enquiry</option><option>Super Stockist enquiry</option><option>Retail supply</option><option>Bulk order</option><option>General enquiry</option></select></div><div className="field full"><label>Your message *</label><textarea required rows={6} placeholder="Tell us how we can help"/></div><button className="button full">Send message <span>↗</span></button></form></section>

  <section className="contact-location contact-reveal" id="location"><div><p className="eyebrow">Our location</p><h2>Rooted in coastal Karnataka.</h2><p>Fresh Kind is based in Mangalore, Dakshina Kannada, Karnataka, India.</p><a className="button light" href="https://maps.google.com/?q=Mangalore+Karnataka" target="_blank">Open in Maps ↗</a></div><div className="location-visual"><span>⌖</span><b>Mangalore</b><small>Dakshina Kannada · Karnataka</small><i></i></div></section>
</PageShell>}
