import { PageShell } from "../site-shell";

const types=[["⇄","Distributor","Build territory-level supply and take Fresh Kind to more retailers."],["▦","Super Stockist","Manage larger inventory and support wider regional distribution."],["⌂","Retail Partner","Add a colourful, growing beverage range to your store."],["◆","Institutional Buyer","Connect with us for hospitality, events and bulk requirements."]];
const steps=[["01","Apply","Share your business and territory details."],["02","Discussion","Our team connects with you directly."],["03","Territory review","We understand the opportunity in your market."],["04","Commercial discussion","Supply terms and quantities are discussed."],["05","Approval","Complete the partnership onboarding process."],["06","Start distribution","Receive products and begin market expansion."]];

export default function Partnership(){return <PageShell accent="#e3ad20">
  <section className="partner-page-hero"><div><p className="eyebrow">A fresh business opportunity</p><h1>Grow your market<br/><span>with Fresh Kind.</span></h1><p>Join our growing network of distributors, super stockists and retail partners—and take a vibrant portfolio of fruit beverages to more customers.</p><div className="partner-hero-actions"><a className="button" href="#apply">Apply as a partner ↗</a><a className="button light" href="https://wa.me/919741189488">WhatsApp our team</a></div><div className="partner-trust"><span><b>30+</b> products</span><span><b>Multiple</b> flavours</span><span><b>Growing</b> opportunity</span></div></div><div className="partner-hero-image"><img src="/assets/partnership-handshake.png" alt="Fresh Kind bottles joining hands in partnership"/></div></section>

  <section className="partner-type-section partner-reveal"><div className="partner-section-heading"><p className="eyebrow">Choose your path</p><h2>A partnership for every kind of market.</h2><p>Whether you manage a territory, a store or commercial purchasing, there is a way to grow with Fresh Kind.</p></div><div className="partner-type-grid">{types.map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p><a href="#apply">Start enquiry ↗</a></article>)}</div></section>

  <section className="partner-benefits partner-reveal"><div className="benefit-image"><img src="/assets/range-momentum-bottle.png" alt="Fresh Kind chiku juice range presentation"/></div><div className="benefit-copy"><p className="eyebrow">Why Fresh Kind</p><h2>A range made to create momentum.</h2><ul><li><i>✦</i><div><b>Growing product range</b><span>Multiple fruit and speciality beverages create more choice.</span></div></li><li><i>●</i><div><b>Distinctive presentation</b><span>Bold packaging is designed to stand out on the shelf.</span></div></li><li><i>↗</i><div><b>Built for more markets</b><span>A brand focused on expanding through dependable relationships.</span></div></li></ul></div></section>

  <section className="partner-process partner-reveal"><div className="partner-section-heading"><p className="eyebrow">How partnership works</p><h2>From first conversation to market launch.</h2></div><div className="partner-step-grid">{steps.map((x,i)=><article key={x[0]}><b>{x[0]}</b><i></i><h3>{x[1]}</h3><p>{x[2]}</p>{i<steps.length-1&&<span>→</span>}</article>)}</div></section>

  <section className="partner-application" id="apply"><div className="application-intro"><p className="eyebrow">Partner application</p><h2>Tell us about your market.</h2><p>Share a few details about your business. Our team will review the opportunity and contact you for the next conversation.</p><div className="application-contact"><i>◉</i><div><b>Prefer WhatsApp?</b><a href="https://wa.me/919741189488">Chat with +91 97411 89488 ↗</a></div></div></div><form><div className="field"><label>Full name *</label><input required placeholder="Your name"/></div><div className="field"><label>Company name *</label><input required placeholder="Business name"/></div><div className="field"><label>Phone number *</label><input required placeholder="+91"/></div><div className="field"><label>Email address *</label><input required type="email" placeholder="you@company.com"/></div><div className="field"><label>Partnership type *</label><select defaultValue=""><option value="" disabled>Select type</option><option>Distributor</option><option>Super Stockist</option><option>Retailer</option><option>Institutional Buyer</option></select></div><div className="field"><label>Market *</label><input required placeholder="City / District / State"/></div><div className="field full"><label>Business and preferred territory</label><textarea rows={5} placeholder="Tell us about your existing business, network and the area you want to serve"/></div><label className="partner-consent full"><input type="checkbox" required/> I agree to be contacted by Fresh Kind regarding this partnership enquiry.</label><button className="button full">Submit application <span>↗</span></button></form></section>
</PageShell>}
